# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e6732105889d3f4a7f384c64e41ab80b293571170fae8b8183af0f41226348b6d63bb2c33245ec8aaaf85c32d782b859cb16ee46d7784f07933fb8f1156f20

test:
  secret_key_base: b32c68de6775b7472786a304fb299a76a4c4a219b21a187818e69d3d45ef173ebbdd4bfa5058ecb77067d76138fad21361428586d3f3d92ca1934adf62cf1504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
